name: Playwright Tests
on: push

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  playwright-staging:
    name: 'Playwright Tests - Staging'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.61.1-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run tests on Staging
        run: pw:run:prod #npx playwright test --grep-invert "registrationPositiveTests"
        env:
          ENVIRONMENT: staging
      - name: Save Staging report
        uses: actions/upload-artifact@v4
        with:
          path: playwright-report/
          name: Staging report
          retention-days: 30
        if: always()

  playwright-prod:
    name: 'Playwright Tests - Production'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.61.1-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run tests on Production
        run: pw:run:staging #npx playwright test --grep-invert "registrationPositiveTests"
        env:
          ENVIRONMENT: prod
      - name: Save Production report
        uses: actions/upload-artifact@v4
        with:
          path: playwright-report/
          name: Production report
        if: always()
      - name: Configure GitHub Pages
        if: always()
        uses: actions/configure-pages@v5
      - name: Upload Pages Artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report/

  deploy:
    if: always()
    needs: playwright-prod
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
